# Generated by Django 5.0.14 on 2026-10-08 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_alter_motocicleta_anio_alter_motocicleta_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
