# Generated by Django 5.0.14 on 2026-10-08 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_alter_motocicleta_anio_alter_motocicleta_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='marca',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]+$', 'Error: Usa solo letras y números.')]),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='modelo',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-]+$', 'Error: Usa solo letras, números y guiones.')]),
        ),
        migrations.AddConstraint(
            model_name='motocicleta',
            constraint=models.CheckConstraint(check=models.Q(('anio__gte', 1900), ('anio__lte', 2027)), name='chk_anio_valido'),
        ),
        migrations.AddConstraint(
            model_name='motocicleta',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0), ('stock__lte', 100)), name='chk_stock_valido'),
        ),
        migrations.AddConstraint(
            model_name='motocicleta',
            constraint=models.CheckConstraint(check=models.Q(('precio__gte', 1), ('precio__lte', 10000000)), name='chk_precio_valido'),
        ),
    ]
